name: integration

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: update dep
          run:  composer update
      - name: phpcs lint
          run: 	composer run-script phpcs -- --standard=PSR12 src bin